# Generated by Django 3.0.2 on 2020-02-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersinfoanalysis',
            old_name='customer_id',
            new_name='customer_email',
        ),
    ]
