# Generated by Django 2.2.6 on 2019-11-17 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20191103_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomersInfo',
            new_name='CustomersInfoCsv',
        ),
        migrations.CreateModel(
            name='CustomersInfoAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('monetary', models.IntegerField()),
                ('customer_id', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('avg_monetary', models.FloatField()),
                ('recency', models.IntegerField()),
                ('first_purchase', models.IntegerField()),
                ('avg_days', models.FloatField()),
                ('std_dev_days', models.FloatField()),
                ('score_frequency', models.IntegerField()),
                ('score_monetary', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfoBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_frequency', models.FloatField()),
                ('boundary_monetary', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
