# Generated by Django 2.2.6 on 2019-11-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_spreadsheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheetinfo',
            name='client_secret_file',
            field=models.FileField(upload_to='path'),
        ),
    ]
